apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: {{ .Values.database.port}}
      targetPort: {{ .Values.database.port}}