apiVersion: v1
kind: Service
metadata:
  name: {{ include "task-app.fullname" . }}
  labels:
    {{- include "task-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port}}
      targetPort: {{ .Values.app.port}}
      protocol: TCP
      name: http
  selector:
    {{- include "task-app.selectorLabels.app" . | nindent 4 }}
