apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: prod
spec:
  selector:
    app: app
  ports:
      - port: 9000
        targetPort: 9000
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ineutrono/task-app:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: task-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            #w8 30 second after start
            initialDelaySeconds: 30
            #send request every 10sec if failed after many times kill container and restart
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0




          